### ISSUE TITLE
No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.

### ISSUE THREAD

**Issue by JohnMaguire** [Novik/ruTorrent#2571]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: 117.0.1 (64-bit)
ruTorrent: v4.2.6-hotfix
PHP: 8.2.7
OS: Debian 12.1

### Tell us how you installed ruTorrent

rtorrent ansible:

```
---
- name: Create rtorrent user
  user:
    name: rtorrent
    state: present
    home: /config/rtorrent

- name: Install rtorrent
  apt:
    name: rtorrent
    state: present
    update_cache: true
  notify: restart rtorrent

- name: Place rtorrent.rc
  copy:
    src: rtorrent.rc
    dest: /config/rtorrent/.rtorrent.rc
    owner: rtorrent
    group: rtorrent
  notify: restart rtorrent

- name: Create rtorrent.d
  file:
    state: directory
    path: /config/rtorrent/rtorrent.d
    owner: rtorrent
    group: rtorrent

- name: Create rTorrent directories
  file:
    state: directory
    path: "{{ item }}"
    owner: rtorrent
    group: rtorrent
  loop:
    # TODO bind mount
    - /downloads/Downloads
    - /config/rtorrent
    - /config/log/rtorrent

- name: Place move-on-completion.rc
  copy:
    src: move-on-completion.rc
    dest: /config/rtorrent/rtorrent.d/move-on-completion.rc
    owner: rtorrent
    group: rtorrent
  notify: restart rtorrent

- name: Place systemd service file
  copy:
    src: rtorrent.service
    dest: /etc/systemd/system/rtorrent.service
  register: rtorrent_service

- systemd:
    daemon_reload: true
  when: rtorrent_service.changed

- name: Autostart rtorrent and start service
  service:
    name: rtorrent
    state: started
    enabled: true
```

rutorrent ansible:

```
---
# TODO Move this to a separate Ansible role?
- name: Install php-fpm
  apt:
    name: php8.2-fpm
    state: present

- name: Ensure php-fpm is enabled and running
  systemd:
    name: php8.2-fpm
    state: started
    enabled: yes
    daemon_reload: yes

# TODO download latest version & symlink
- name: Download and extract ruTorrent
  unarchive:
    src: https://github.com/Novik/ruTorrent/archive/refs/tags/v4.2.6.tar.gz
    dest: /var/www
    remote_src: yes
    creates: /var/www/rutorrent
    extra_opts:
      - --transform
      - 's/^[a-zA-Z]\+-[0-9.]\+/rutorrent/'

- name: Chown ruTorrent directory
  file:
    state: directory
    path: /var/www/rutorrent
    owner: www-data
    group: www-data
    mode: u=rwX,g=rX,o=rX
    recurse: true

- name: Create ruTorrent log directories
  file:
    state: directory
    path: "{{ item }}"
    owner: www-data
    group: www-data
  loop:
    - /config/log/rutorrent
    # TODO move this to nginx?
    - /config/log/nginx

- name: Configure ruTorrent
  replace:
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
    path: /var/www/rutorrent/conf/config.php
  loop:
    - regexp: 'scgi_port = 5000;'
      replace: 'scgi_port = 0;'
    - regexp: 'scgi_host = "127.0.0.1";'
      replace: 'scgi_host = "unix:///tmp/rtorrent.sock";'
    - regexp: 'localHostedMode = false;'
      replace: 'localHostedMode = true;'
    - regexp: "log_file = '/tmp/errors.log';"
      replace: "log_file = '/config/log/rutorrent/rutorrent.log';"

- name: Install ruTorrent nginx conf
  copy:
    src: rutorrent.conf
    dest: /etc/nginx/sites-available/rutorrent.conf
  notify: reload nginx

- name: Give nginx access to rTorrent socket file
  user:
    name: www-data
    groups: rtorrent
    append: yes

- name: Enable ruTorrent nginx conf
  file:
    src: /etc/nginx/sites-available/rutorrent.conf
    dest: /etc/nginx/sites-enabled/rutorrent.conf
    state: link
  notify: reload nginx
```

### Describe the bug

I get the following message when loading ruTorrent:

```
[15.09.2023 14:51:10] No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.
```

### Steps to reproduce

Attempt to load ruTorrent UI.

### Expected behavior

ruTorrent UI should load correctly.

### Additional context

Running the following test as `www-data` works successfully:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Quick XMLRPC connection test via /RPC2"""
import sys
import socket
from xmlrpc import client
from datetime import datetime


def main(args):
    """XMLRPC /RPC2 test."""
    host = 'localhost'
    if len(args) >= 1:
        host = args[0]
    url = "http://{}/RPC2".format(host)
    print("Connecting to {!r}...".format(url))
    server = client.ServerProxy(url)
    print(server)

    try:
        print("Session:         %s" % server.session.name())
        print("XMLRPC methods:  %d" % len(server.system.listMethods()))
        time_usec = server.system.time_usec()
        print("Time (µsec):     %d (%s)" % (
            time_usec, datetime.fromtimestamp(time_usec/1E6).isoformat()))
    except (socket.error, client.Error) as cause:
        print("ERROR: %s" % cause)
        return 1
    else:
        print("OK")


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
```

rtorrent.rc:

```
#############################################################################
# A minimal rTorrent configuration that provides the basic features
# you want to have in addition to the built-in defaults.
#
# See https://github.com/rakshasa/rtorrent/wiki/CONFIG-Template
# for an up-to-date version.
#############################################################################

# Instance layout (base paths)
method.insert = cfg.basedir,    private|const|string, (cat,"/downloads/Downloads/")
method.insert = cfg.confdir,    private|const|string, (cat,"/config/rtorrent/")
method.insert = cfg.completed,  private|const|string, (cat,(cfg.basedir),"completed/")
method.insert = cfg.incomplete, private|const|string, (cat,(cfg.basedir),"incomplete/")
method.insert = cfg.watch,      private|const|string, (cat,(cfg.basedir),"watch/")
method.insert = cfg.session,    private|const|string, (cat,(cfg.confdir),".session/")
method.insert = cfg.logdir,     private|const|string, (cat,"/config/log/rtorrent/")
method.insert = cfg.logfile,    private|const|string, (cat,(cfg.logdir),"rtorrent-",(system.time),".log")
method.insert = cfg.socketdir,  private|const|string, (cat,"/tmp/")
method.insert = cfg.socket,     private|const|string, (cat,(cfg.socketdir),"rtorrent.sock")

# Create instance directories
execute.throw = sh, -c, (cat,\
    "mkdir -p \"",(cfg.completed),"\" ",\
    "\"",(cfg.incomplete),"\" ",\
    "\"",(cfg.logdir),"\" ",\
    "\"",(cfg.session),"\" ",\
    "\"",(cfg.socketdir),"\" ",\
    "\"",(cfg.watch),"\" ")

# Listening port for incoming peer traffic (fixed; you can also randomize it)
network.port_range.set = 51413-51413
network.port_random.set = no

# Tracker-less torrent and UDP tracker support
# (conservative settings for 'private' trackers, change for 'public')
dht.mode.set = disable
protocol.pex.set = no
trackers.use_udp.set = no

# Peer settings
## Slots per torrent
throttle.max_uploads.set = 128
throttle.max_downloads.set = 128

throttle.max_uploads.global.set = 0
throttle.max_downloads.global.set = 1024

throttle.min_peers.normal.set = 128
throttle.max_peers.normal.set = 256
throttle.min_peers.seed.set = -1
throttle.max_peers.seed.set = -1
trackers.numwant.set = 800

protocol.encryption.set = allow_incoming,try_outgoing,enable_retry

# Limits for file handle resources, this is optimized for
# an `ulimit` of 1024 (a common default). You MUST leave
# a ceiling of handles reserved for rTorrent's internal needs!
network.http.max_open.set = 50
network.max_open_files.set = 600
network.max_open_sockets.set = 300

# Memory resource usage (increase if you have a large number of items loaded,
# and/or the available resources to spend)
pieces.memory.max.set = 2048M
network.xmlrpc.size_limit.set = 4M

# Basic operational settings (no need to change these)
session.path.set = (cat, (cfg.session))
directory.default.set = (cat, (cfg.incomplete))
log.execute = (cat, (cfg.logdir), "execute.log")
log.xmlrpc = (cat, (cfg.logdir), "xmlrpc.log")
execute.nothrow = sh, -c, (cat, "echo >",\
    (session.path), "rtorrent.pid", " ", (system.pid))

# Other operational settings (check & adapt)
encoding.add = utf8
system.umask.set = 0027
system.cwd.set = (directory.default)
network.http.dns_cache_timeout.set = 25
schedule2 = monitor_diskspace, 15, 60, ((close_low_diskspace, 1000M))
##pieces.hash.on_completion.set = no
##view.sort_current = seeding, greater=d.ratio=
##keys.layout.set = qwerty
##network.http.capath.set = "/etc/ssl/certs"
##network.http.ssl_verify_peer.set = 0
##network.http.ssl_verify_host.set = 0

# Some additional values and commands
method.insert = system.startup_time, value|const, (system.time)
method.insert = d.data_path, simple,\
    "if=(d.is_multi_file),\
        (cat, (d.directory), /),\
        (cat, (d.directory), /, (d.name))"
method.insert = d.session_file, simple, "cat=(session.path), (d.hash), .torrent"

# Watch directories (add more as you like, but use unique schedule names)
schedule2 = watch_start, 10, 10, ((load.start_verbose, (cat, (cfg.watch), ".torrent")))

# Run the rTorrent process as a daemon in the background
system.daemon.set = true

# ruTorrent
execute.nothrow = rm, (cat,(cfg.socket))
network.scgi.open_local = (cat,(cfg.socket))
schedule2 = socket_chmod, 0, 0, "execute.throw=chmod,0660,(cat,(cfg.socket))"
schedule2 = socket_chgrp, 0, 0, "execute.throw=chgrp,rtorrent,(cat,(cfg.socket))"

# Logging:
#   Levels = critical error warn notice info debug
#   Groups = connection_* dht_* peer_* rpc_* storage_* thread_* tracker_* torrent_*
print = (cat, "Logging to ", (cfg.logfile))
log.open_file = "log", (cfg.logfile)
log.add_output = "info", "log"
##log.add_output = "tracker_debug", "log"

# rtorrent.d config directory
method.insert = cfg.drop_in, private|const|string, (cat, (cfg.confdir), "rtorrent.d/")
try_import = (cat, (cfg.drop_in), ".import")

### END of rtorrent.rc ###
```

config.php:

```
<?php
	// configuration parameters

	// for snoopy client
	$httpUserAgent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36';
	$httpTimeOut = 30;			// in seconds
	$httpUseGzip = true;
	$httpIP = null;				// IP string. Or null for any.
	$httpProxy = array
	(
		'use'	=> false,
		'proto'	=> 'http',		// 'http' or 'https'
		'host'	=> 'PROXY_HOST_HERE',
		'port'	=> 3128
	);

	// for xmlrpc actions
	$rpcTimeOut = 5;			// in seconds
	$rpcLogCalls = false;
	$rpcLogFaults = true;

	// for php
	$phpUseGzip = false;
	$phpGzipLevel = 2;

	$schedule_rand = 10;			// rand for schedulers start, +0..X seconds

	$do_diagnostic = true;			// Diagnose ruTorrent. Recommended to keep enabled, unless otherwise required.
	$al_diagnostic = true;			// Diagnose auto-loader. Set to "false" to make composer plugins work.

	$log_file = '/config/log/rutorrent/rutorrent.log';		// path to log file (comment or leave blank to disable logging)

	$saveUploadedTorrents = true;		// Save uploaded torrents to profile/torrents directory or not
	$overwriteUploadedTorrents = false;	// Overwrite existing uploaded torrents in profile/torrents directory or make unique name

	$topDirectory = '/';			// Upper available directory. Absolute path with trail slash.
	$forbidUserSettings = false;

	$scgi_port = 0;
	$scgi_host = "unix:///tmp/rtorrent.sock";

	// For web->rtorrent link through unix domain socket
	// (scgi_local in rtorrent conf file), change variables
	// above to something like this:
	//
	// $scgi_port = 0;
	// $scgi_host = "unix:///tmp/rpc.socket";

	$XMLRPCMountPoint = "/RPC2";		// DO NOT DELETE THIS LINE!!! DO NOT COMMENT THIS LINE!!!

	$throttleMaxSpeed = 327625*1024;	// DO NOT EDIT THIS LINE!!! DO NOT COMMENT THIS LINE!!!
	// Can't be greater then 327625*1024 due to limitation in libtorrent ResourceManager::set_max_upload_unchoked function.

	$pathToExternals = array(
		"php"	=> '',			// Something like /usr/bin/php. If empty, will be found in PATH.
		"curl"	=> '',			// Something like /usr/bin/curl. If empty, will be found in PATH.
		"gzip"	=> '',			// Something like /usr/bin/gzip. If empty, will be found in PATH.
		"id"	=> '',			// Something like /usr/bin/id. If empty, will be found in PATH.
		"stat"	=> '',			// Something like /usr/bin/stat. If empty, will be found in PATH.
	);

	$localHostedMode = true;		// Set to true if rTorrent is hosted on the SAME machine as ruTorrent

	$cachedPluginLoading = false;		// Set to true to enable rapid cached loading of ruTorrent plugins
										// Required to clear web browser cache when upgrading versions

	$localhosts = array(			// list of local interfaces
		"127.0.0.1",
		"localhost",
	);

	$profilePath = '../../share';		// Path to user profiles
	$profileMask = 0777;			// Mask for files and directory creation in user profiles.
						// Both Webserver and rtorrent users must have read-write access to it.
						// For example, if Webserver and rtorrent users are in the same group then the value may be 0770.

	$tempDirectory = null;			// Temp directory. Absolute path with trail slash. If null, then autodetect will be used.

	$canUseXSendFile = false;		// If true then use X-Sendfile feature if it exist

	$locale = "UTF8";

	$enableCSRFCheck = false;		// If true then Origin and Referer will be checked
	$enabledOrigins = array();		// List of enabled domains for CSRF check (only hostnames, without protocols, port etc.).
						// If empty, then will retrieve domain from HTTP_HOST / HTTP_X_FORWARDED_HOST
```

nginx conf:

```
upstream backendphp {
    server unix:/run/php/php8.2-fpm.sock;
}

upstream backendrtorrent {
    server unix:/tmp/rtorrent.sock;
}

server {
    listen 80 default_server;

    root /var/www/rutorrent;
    index index.php index.html index.htm;

    server_name _;

    client_max_body_size 0;

    location / {
        location ~ .php$ {
            fastcgi_split_path_info ^(.+\.php)(.*)$;
            fastcgi_pass backendphp;
            fastcgi_index index.php;
            include /etc/nginx/fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }

    location /RPC2 {
        access_log /config/log/nginx/rutorrent.rpc2.access.log;
        error_log /config/log/nginx/rutorrent.rpc2.error.log;
        include /etc/nginx/scgi_params;
        scgi_pass backendrtorrent;
    }
}
```

```
root@demeter-torrent:~# ls -l /tmp/rtorrent.sock
srw-rw---- 1 rtorrent rtorrent 0 Sep 15 18:39 /tmp/rtorrent.sock
```

**NOTE:** `/config/log/rutorrent/rutorrent.log` is empty.
