### ISSUE TITLE
Consecutive spaces in the torrent description are collapsed by default

### ISSUE THREAD

**Issue by sio** [Novik/ruTorrent#995]
Copying a path from the torrent description fails: if the path has consecutive spaces in it, the copied text will not be a valid filesystem path because by default HTML collapses consecutive spaces into one.

This is easily fixed by CSS:
````css
/* Do not collapse consecutive spaces in the "Save As" line */
#bf {white-space:pre}
````
The example above was written for older rutorrent version but you get the idea
